-- Canonical magic catalog reference.
-- Read-only file. Existing DB migration uses `03_migrate_magic_references.sql`.
WITH magic_catalog(id, name) AS (
    VALUES
        (1, 'ember_spirit_swarm'),
        (2, 'water_slime_swarm'),
        (3, 'mini_rock_swarm'),
        (4, 'seed_spirit_swarm'),
        (5, 'wind_spirit'),
        (6, 'water_shot'),
        (7, 'fire_shot'),
        (8, 'tide_call'),
        (9, 'chain_lightning'),
        (10, 'vine_toss'),
        (11, 'rock_rolling'),
        (12, 'wind_blade'),
        (13, 'nature_shot'),
        (14, 'fire_slime_nest'),
        (15, 'water_slime_nest'),
        (16, 'life_tree'),
        (17, 'rock_turret'),
        (18, 'wind_totem'),
        (19, 'magma_explosion'),
        (20, 'water_explosion'),
        (21, 'will_o_wisp'),
        (22, 'nature_explosion'),
        (23, 'frenzy_totem'),
        (24, 'leafair'),
        (25, 'cannon'),
        (26, 'tower'),
        (27, 'mana_well'),
        (28, 'aqua_archer'),
        (29, 'rock_golem'),
        (30, 'storm_rider'),
        (31, 'thunder_spirit'),
        (32, 'fire_spirit'),
        (33, 'rock_shot'),
        (35, 'lightning_drop'),
        (36, 'wind_explosion'),
        (37, 'rock_explosion'),
        (38, 'fire_explosion'),
        (39, 'magma_spirit'),
        (40, 'healing_totem'),
        (41, 'sand_storm'),
        (42, 'wind_slime_swarm'),
        (43, 'tornado_strike'),
        (44, 'meteor_shower'),
        (45, 'lightning_shot'),
        (46, 'cloud_dragon'),
        (47, 'thunder_bird_swarm'),
        (48, 'tree_golem'),
        (49, 'vine_spirit'),
        (50, 'vine_colony'),
        (51, 'rock_mage'),
        (52, 'pve_nature_slime_nest'),
        (53, 'pve_vine'),
        (54, 'rock_drop'),
        (55, 'chicken_commando'),
        (56, 'overgrowth'),
        (57, 'crater'),
        (58, 'zap_mouse'),
        (59, 'rallying_torch'),
        (60, 'lightning_explosion'),
        (61, 'razor_gale'),
        (62, 'bubble_generator'),
        (63, 'electric_tower'),
        (64, 'fire_lord_spirit'),
        (65, 'dimension_toad'),
        (66, 'towerback'),
        (67, 'shock_overload'),
        (68, 'bubble_spirit')
)
SELECT id, name
FROM magic_catalog
ORDER BY id;
